//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.23 at 10:56:32 AM MSK 
//


package mgfoms.ru.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mgfoms.ru.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mgfoms.ru.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterChangeRequest2222 }
     * 
     */
    public RegisterChangeRequestObject createRegisterChangeRequest() {
        return new RegisterChangeRequestObject();
    }

    /**
     * Create an instance of {@link WsAuthInfo }
     * 
     */
    public WsAuthInfo createWsAuthInfo() {
        return new WsAuthInfo();
    }

    /**
     * Create an instance of {@link RegisterChangeResponse }
     * 
     */
    public RegisterChangeResponse createRegisterChangeResponse() {
        return new RegisterChangeResponse();
    }

    /**
     * Create an instance of {@link RegisterReceiptRequest22222 }
     * 
     */
    public RegisterReceiptRequestObject createRegisterReceiptRequest() {
        return new RegisterReceiptRequestObject();
    }

    /**
     * Create an instance of {@link RegisterReceiptResponse }
     * 
     */
    public RegisterReceiptResponse createRegisterReceiptResponse() {
        return new RegisterReceiptResponse();
    }

    /**
     * Create an instance of {@link GetDocListRequest2222 }
     * 
     */
    public GetDocListRequestObject createGetDocListRequest() {
        return new GetDocListRequestObject();
    }

    /**
     * Create an instance of {@link GetDocListResponse }
     * 
     */
    public GetDocListResponse createGetDocListResponse() {
        return new GetDocListResponse();
    }

    /**
     * Create an instance of {@link DocMetadata }
     * 
     */
    public DocMetadata createDocMetadata() {
        return new DocMetadata();
    }

    /**
     * Create an instance of {@link GetDocRequest2222 }
     * 
     */
    public GetDocRequestObject createGetDocRequest() {
        return new GetDocRequestObject();
    }

    /**
     * Create an instance of {@link GetDocResponse }
     * 
     */
    public GetDocResponse createGetDocResponse() {
        return new GetDocResponse();
    }

    /**
     * Create an instance of {@link GetMailGw202110Request }
     * 
     */
    public GetMailGw202110Request createGetMailGw202110Request() {
        return new GetMailGw202110Request();
    }

    /**
     * Create an instance of {@link GetMailGw202110Response }
     * 
     */
    public GetMailGw202110Response createGetMailGw202110Response() {
        return new GetMailGw202110Response();
    }

    /**
     * Create an instance of {@link FindMailGwLogs202110Response }
     * 
     */
    public FindMailGwLogs202110Response createFindMailGwLogs202110Response() {
        return new FindMailGwLogs202110Response();
    }

    /**
     * Create an instance of {@link FindMailGwLogBean202110 }
     * 
     */
    public FindMailGwLogBean202110 createFindMailGwLogBean202110() {
        return new FindMailGwLogBean202110();
    }

}
