package ru.ibs.docxtestproject;

import java.io.IOException;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.function.Supplier;
import org.hibernate.SessionFactory;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean;

public class RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWordLauncher {

	public static void start(String[] args, Supplier<SessionFactory> getSessionFactory) throws IOException {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean = createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean();
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean = createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean();
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection1 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, 88d, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, 488d, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection2 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, 88d, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, 488d, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection3 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, 88d, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, 488d, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection4 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, 88d, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, 488d, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBeanCollection = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean(8888, "iotd", 888888L, new Date(), 8888d, 12345678d, 222d, 42d, 80d, 120d), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean(4444, "iotd4", 44L, new Date(), 22d, 44d, 66d, 88d, 10d, 20d));
		String path = args[0];
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord.create(registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection1, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection2, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection3, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection4, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBeanCollection, path);
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean() {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setLpuFullName("Интересная ЛПУ");
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setPeriod(new Date());
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setPeriodStr("Какой-то период");
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setCaseIdCount(22222);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setServiceSum(88888888d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setCaseIdCount2Stationary(22);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setServiceSum2Stationary(88d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setCaseIdCount3NotAccepted(44);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setServiceSum3NotAccepted(8888d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setLastSendingDate(new Date());
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean;
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean() {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1TotalServiceCount(100);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1TotalServiceSum(1000d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row2ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row3ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row3ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row4ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row4ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2TotalServiceCount(100);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2TotalServiceSum(1000d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row2ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row3ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row3ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row4ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row4ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3TotalServiceCount(100);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3TotalServiceSum(1000d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row2ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row3ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row3ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row4ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row4ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row2ServiceSum(10d);
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean;
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(Integer filId, String iotd, Long billId, Date period, String policyNumber, Integer territoryCode, String violationCode, Double serviceSum, Integer financialSanctionsCode, Double financialSanctionsSum, String otherViolationCodes) {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setFilId(filId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setIotd(iotd);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setBillId(billId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setPeriod(period);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setPolicyNumber(policyNumber);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setTerritoryCode(territoryCode);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setViolationCode(violationCode);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setServiceSum(serviceSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setFinancialSanctionsCode(financialSanctionsCode);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setFinancialSanctionsSum(financialSanctionsSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setOtherViolationCodes(otherViolationCodes);
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean;
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean(Integer filId, String iotd, Long billId, Date period, Double excessSum, Double serviceSum, Double notAcceptedServiceSum, Double notAcceptedServiceSumBeforeRepeatedCheck, Double holdedServiceSum, Double serviceSumThatShouldBeHoldedOnTheNextPeriod) {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setFilId(filId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setIotd(iotd);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setBillId(billId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setPeriod(period);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setExcessSum(excessSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setNotAcceptedServiceSum(notAcceptedServiceSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setNotAcceptedServiceSumBeforeRepeatedCheck(notAcceptedServiceSumBeforeRepeatedCheck);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setHoldedServiceSum(holdedServiceSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setServiceSumThatShouldBeHoldedOnTheNextPeriod(serviceSumThatShouldBeHoldedOnTheNextPeriod);
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean;
	}
}
