package ru.ibs.docxtestproject;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.function.Supplier;
import org.hibernate.SessionFactory;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean;
import ru.ibs.docxtestproject.bean.RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean;
import ru.ibs.testpumputils.utils.FieldUtil;

public class RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWordLauncher {

	public static void start(String[] args, Supplier<SessionFactory> getSessionFactory) throws IOException, ParseException {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean = createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean();
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean = createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean();
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection1 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection2 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection3 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection4 = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(5555, "iotd", 22L, new Date(), "policyNumber", 77, "violationCode", 12d, 88, "other"), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(4444, "iotd22", 44L, new Date(), "policyNumber2", 88, "violationCode2", 312d, 588, "other2"));
		Collection<RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean> registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBeanCollection = Arrays.asList(createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean(8888, "iotd", 888888L, new Date(), 8888d, 2, 222d, 42d, 80d, 120d), createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean(4444, "iotd4", 44L, new Date(), 22d, 2, 66d, 88d, 10d, 20d));
		String path = args[0];
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord();
		FieldUtil.setField(registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord, getSessionFactory.get(), "smoSessionFactory");
//		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord.create(registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection1, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection2, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection3, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBeanCollection4, registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBeanCollection, path);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlWord.create(1962L, new SimpleDateFormat("yyyy-MM-dd").parse("2022-02-01"), 1415550L, args[0]);
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean() {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setDateCrt(new Date());
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setDateSend(new Date());
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setLastDay("lastDay");
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setMoName("Интересная ЛПУ");
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setNum(5);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean.setPeriodStr("Какой-то период");
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlHeadBean;
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean() {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1TotalServiceCount(100);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1TotalServiceSum(1000d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row2ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row3ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row3ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row4ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter1Row4ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2TotalServiceCount(100);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2TotalServiceSum(1000d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row2ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row3ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row3ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row4ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter2Row4ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3TotalServiceCount(100);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3TotalServiceSum(1000d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row2ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row3ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row3ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row4ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter3Row4ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row1ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row1ServiceSum(10d);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row2ServiceCount(10);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean.setChapter4Row2ServiceSum(10d);
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlFirstTableBean;
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean(Integer filId, String iotd, Long billId, Date period, String policyNumber, Integer territoryCode, String violationCode, Double serviceSum, Integer financialSanctionsCode, String otherViolationCodes) {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setFilId(filId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setIotd(iotd);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setBillId(billId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setDateMn(period);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setPolicyNumber(policyNumber);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setTerritoryCode(territoryCode);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setErrorCode(violationCode);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setServiceSum(serviceSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setFinancialSanctionsCode(financialSanctionsCode.toString());
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean.setOtherErrorCodes(otherViolationCodes);
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlSecondTableBean;
	}

	private static RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean createRegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean(Integer filId, String iotd, Long billId, Date period, Double excessSum, Integer quarter, Double notAcceptedServiceSum, Double notAcceptedServiceSumBeforeRepeatedCheck, Double holdedServiceSum, Double serviceSumThatShouldBeHoldedOnTheNextPeriod) {
		RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean = new RegisterOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean();
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setFilId(filId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setIotd(iotd);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setBillId(billId);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setQuarter(quarter);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setExcessSum(excessSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setNotAcceptedServiceSum(notAcceptedServiceSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setNotAcceptedServiceSumBeforeRepeatedCheck(notAcceptedServiceSumBeforeRepeatedCheck);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setHoldedServiceSum(holdedServiceSum);
		registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean.setServiceSumThatShouldBeHoldedOnTheNextPeriod(serviceSumThatShouldBeHoldedOnTheNextPeriod);
		return registerOfConclusionsBasedOnTheResultsOfMedicalAndEconomicControlThirdTableBean;
	}
}
