//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.23 at 10:56:32 AM MSK 
//


package mgfoms.ru.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mailStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="mailStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="OK"/&gt;
 *     &lt;enumeration value="ERROR"/&gt;
 *     &lt;enumeration value="DELETED"/&gt;
 *     &lt;enumeration value="IGNORED"/&gt;
 *     &lt;enumeration value="IN_QUEUE"/&gt;
 *     &lt;enumeration value="IN_PROCESS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "mailStatus")
@XmlEnum
public enum MailStatus {

    OK,
    ERROR,
    DELETED,
    IGNORED,
    IN_QUEUE,
    IN_PROCESS;

    public String value() {
        return name();
    }

    public static MailStatus fromValue(String v) {
        return valueOf(v);
    }

}
