//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.23 at 10:56:32 AM MSK 
//


package mgfoms.ru.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parcelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="parcelType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="REPORT_IN_SMO"/&gt;
 *     &lt;enumeration value="REPORT_IN_MGFOMS"/&gt;
 *     &lt;enumeration value="REPORT_SMO_IN_MO"/&gt;
 *     &lt;enumeration value="REPORT_MGFOMS_IN_MO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "parcelType")
@XmlEnum
public enum ParcelType {

    REPORT_IN_SMO,
    REPORT_IN_MGFOMS,
    REPORT_SMO_IN_MO,
    REPORT_MGFOMS_IN_MO;

    public String value() {
        return name();
    }

    public static ParcelType fromValue(String v) {
        return valueOf(v);
    }

}
